env: flex
runtime: nodejs
manual_scaling:
  instances: 1
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: lender-184617:us-central1:rosco-dev-1
env_variables:
  SQL_USER: postgres
  SQL_PASSWORD: password
  SQL_DATABASE: rosco-dev-2
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: lender-184617:us-central1:rosco-dev-1
