export const STREET_TYPES = [
    { label: 'Street', value: 'Street' },
    { label: 'Road', value: 'Road' },
    { label: 'Avenue', value: 'Avenue' },
    { label: 'Boulevard', value: 'Boulevard' },
    { label: 'Drive', value: 'Drive' },
    { label: 'Circuit', value: 'Circuit' },
    { label: 'Close', value: 'Close' },
    { label: 'Cresent', value: 'Cresent' },
    { label: 'Court', value: 'Court' },
    { label: 'Highway', value: 'Highway' },
    { label: 'Lane', value: 'Lane' },
    { label: 'Loop', value: 'Loop' },
    { label: 'Place', value: 'Place' },
    { label: 'Point', value: 'Point' },
    { label: 'Parade', value: 'Parade' },
    { label: 'Terrace', value: 'Terrace' },
    { label: 'Way', value: 'Way' },
    { label: 'The Ridge', value: 'The Ridge' },
    { label: 'Bend', value: 'Bend' },
    { label: 'Other', value: 'Other' },
];
